# **Importing the libraries**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# **Importing the dataset**

In [ ]:
from google.colab import files
files.upload()

Saving hepatitis.csv to hepatitis.csv

{'hepatitis.csv': b'age,sex,steroid,antivirals,fatigue,malaise,anorexia,liver_big,liver_firm,spleen_palpable,spiders,ascites,varices,bilirubin,alk_phosphate,sgot,albumin,protime,histology,class\r\n30,male,False,False,False,False,False,False,False,False,False,False,False,1,85,18,4,,False,live\r\n50,female,False,False,True,False,False,False,False,False,False,False,False,0.9,135,42,3.5,,False,live\r\n78,female,True,False,True,False,False,True,False,False,False,False,False,0.7,96,32,4,,False,live\r\n31,female,,True,False,False,False,True,False,False,False,False,False,0.7,46,52,4,80,False,live\r\n34,female,True,False,False,False,False,True,False,False,False,False,False,1,,200,4,,False,live\r\n34,female,True,False,False,False,False,True,False,False,False,False,False,0.9,95,28,4,75,False,live\r\n51,female,False,False,True,False,True,True,False,True,True,False,False,,,,,,False,die\r\n23,female,True,False,False,False,False,True,False,False,False,False,False,1,,,,,False,live\r\n39,female,True,False,True,False,False,True,True,False,False,False,False,0.7,,48,4.4,,False,live\r\n30,female,True,False,False,False,False,True,False,False,False,False,False,1,,120,3.9,,False,live\r\n39,female,False,True,False,False,False,False,True,False,False,False,False,1.3,78,30,4.4,85,False,live\r\n32,female,True,True,True,False,False,True,True,False,True,False,False,1,59,249,3.7,54,False,live\r\n41,female,True,True,True,False,False,True,True,False,False,False,False,0.9,81,60,3.9,52,False,live\r\n30,female,True,False,True,False,False,True,True,False,False,False,False,2.2,57,144,4.9,78,False,live\r\n47,female,False,True,False,False,False,True,False,False,False,False,False,,,60,,,False,live\r\n38,female,False,False,True,True,True,True,False,False,False,True,False,2,72,89,2.9,46,False,live\r\n66,female,True,False,True,False,False,True,False,False,False,False,False,1.2,102,53,4.3,,False,live\r\n40,female,False,False,True,False,False,True,True,False,False,False,False,0.6,62,166,4,63,False,live\r\n38,female,True,False,False,False,False,True,False,False,False,False,False,0.7,53,42,4.1,85,True,live\r\n38,female,False,True,False,False,False,False,True,False,False,False,False,0.7,70,28,4.2,62,False,live\r\n22,male,True,True,True,False,False,True,False,False,False,False,False,0.9,48,20,4.2,64,False,live\r\n27,female,True,False,True,True,True,False,True,True,True,False,False,1.2,133,98,4.1,39,False,live\r\n31,female,True,False,False,False,False,True,False,False,False,False,False,1,85,20,4,100,False,live\r\n42,female,True,False,False,False,False,True,False,False,False,False,False,0.9,60,63,4.7,47,False,live\r\n25,male,False,True,False,False,False,True,False,False,False,False,False,0.4,45,18,4.3,70,False,live\r\n27,female,False,False,True,True,False,True,False,False,False,False,False,0.8,95,46,3.8,100,False,live\r\n49,female,False,True,True,True,True,True,True,False,True,False,False,0.6,85,48,3.7,,False,live\r\n58,male,True,False,True,False,False,True,True,False,True,False,False,1.4,175,55,2.7,36,False,live\r\n61,female,False,False,True,False,False,False,True,False,False,False,False,1.3,78,25,3.8,100,False,live\r\n51,female,False,True,True,True,False,True,False,False,False,False,False,1,78,58,4.6,52,False,live\r\n39,female,False,True,True,True,False,True,True,False,False,False,False,2.3,280,98,3.8,40,False,die\r\n62,female,False,False,True,True,False,,,False,False,False,False,1,,60,,,False,die\r\n41,male,True,True,True,True,True,True,False,False,False,False,False,0.7,81,53,5,74,False,live\r\n26,male,False,False,False,False,False,True,True,False,False,False,False,0.5,135,29,3.8,60,False,live\r\n35,female,True,False,True,False,False,True,False,False,False,False,False,0.9,58,92,4.3,73,False,live\r\n37,female,True,False,True,False,False,True,False,False,True,False,False,0.6,67,28,4.2,,False,die\r\n23,female,True,False,True,True,True,True,False,True,False,False,False,1.3,194,150,4.1,90,False,live\r\n20,male,False,False,True,True,True,False,True,True,True,False,False,2.3,150,68,3.9,,False,live\r\n42,female,False,False,False,False,False,True,False,False,False,False,False,1,85,14,4,100,False,live\r\n65,female,True,False,True,True,False,True,True,True,True,True,False,0.3,180,53,2.9,74,True,live\r\n52,female,False,True,False,False,False,True,False,False,False,False,False,0.7,75,55,4,21,False,live\r\n23,female,True,False,False,False,False,,,,,,,4.6,56,16,4.6,,False,live\r\n33,female,True,False,False,False,False,True,False,False,False,False,False,1,46,90,4.4,60,False,live\r\n56,female,False,False,True,False,False,True,False,False,False,False,False,0.7,71,18,4.4,100,False,live\r\n34,female,True,False,False,False,False,True,False,False,False,False,False,,,86,,,False,live\r\n28,female,True,False,True,True,False,True,False,False,False,False,False,0.7,74,110,4.4,,False,live\r\n37,female,False,False,False,False,False,True,True,False,True,False,False,0.6,80,80,3.8,,False,live\r\n28,male,True,False,True,True,False,True,True,False,False,False,False,1.8,191,420,3.3,46,False,live\r\n36,female,False,False,False,False,False,True,False,True,False,False,False,0.8,85,44,4.2,85,False,live\r\n38,female,True,True,True,True,True,True,False,False,True,False,False,0.7,125,65,4.2,77,False,live\r\n39,female,False,False,False,False,False,True,False,False,False,False,False,0.9,85,60,4,,False,live\r\n39,female,True,False,False,False,False,True,False,False,False,False,False,1,85,20,4,,False,live\r\n44,female,True,False,False,False,False,True,False,False,False,False,False,0.6,110,145,4.4,70,False,live\r\n40,female,True,True,True,False,False,True,True,True,False,False,False,1.2,85,31,4,100,False,live\r\n30,female,True,False,True,False,False,True,False,False,False,False,False,0.7,50,78,4.2,74,False,live\r\n37,female,False,False,True,True,True,True,False,False,False,False,False,0.8,92,59,,,False,live\r\n34,female,False,False,,,,,,,,,,,,,,,False,live\r\n30,female,True,True,False,False,False,True,False,False,False,False,False,0.7,52,38,3.9,52,False,live\r\n64,female,True,True,True,True,False,False,True,False,False,False,False,1,80,38,4.3,74,False,live\r\n45,male,False,False,True,True,False,True,False,True,False,False,False,1,85,75,,,False,live\r\n37,female,True,False,False,False,False,True,False,False,False,False,False,0.7,26,58,4.5,100,False,live\r\n32,female,True,False,False,False,False,True,False,False,False,False,False,0.7,102,64,4,90,False,live\r\n32,female,True,False,True,True,True,True,False,False,True,False,True,3.5,215,54,3.4,29,False,live\r\n36,female,False,False,False,False,False,False,True,True,False,False,False,0.7,164,44,3.1,41,False,live\r\n49,female,True,False,True,True,False,True,False,False,False,False,False,0.8,103,43,3.5,66,False,live\r\n27,female,True,False,False,False,False,True,False,False,False,False,False,0.8,,38,4.2,,False,live\r\n56,female,False,False,False,False,False,True,False,False,False,False,False,0.7,62,33,3,,False,live\r\n57,female,True,False,True,True,True,True,False,False,True,True,False,4.1,,48,2.6,73,False,die\r\n39,female,True,False,True,False,False,True,False,False,False,False,False,1,34,15,4,54,False,live\r\n44,female,False,False,True,True,False,True,False,False,False,False,False,1.6,68,68,3.7,,False,live\r\n24,female,True,False,False,False,False,True,False,False,False,False,False,0.8,82,39,4.3,,False,live\r\n34,female,False,False,True,True,False,False,True,False,True,False,False,2.8,127,182,,,False,die\r\n51,female,True,False,True,True,True,,,,,,,0.9,76,271,4.4,,False,live\r\n36,female,False,False,True,True,True,True,True,False,False,False,False,1,,45,4,57,False,live\r\n50,female,True,False,False,False,False,True,False,False,False,False,False,1.5,100,100,5.3,,False,live\r\n32,female,False,True,True,True,False,True,False,False,False,False,False,1,55,45,4.1,56,False,live\r\n58,female,True,False,True,False,False,False,True,True,True,False,False,2,167,242,3.3,,False,die\r\n34,male,False,True,False,False,False,True,True,False,False,False,False,0.6,30,24,4,76,False,live\r\n34,female,False,False,True,False,False,False,True,False,True,False,False,1,72,46,4.4,57,False,live\r\n28,female,True,False,False,False,False,True,False,False,False,False,False,0.7,85,31,4.9,,False,live\r\n23,female,True,False,True,True,True,True,False,False,False,False,False,0.8,,14,4.8,,False,live\r\n36,female,True,False,False,False,False,True,False,False,False,False,False,0.7,62,224,4.2,100,False,live\r\n30,female,False,False,False,False,False,True,False,False,False,False,False,0.7,100,31,4,100,False,live\r\n67,male,False,False,True,True,False,True,False,,,,,1.5,179,69,2.9,,False,live\r\n62,male,True,False,True,True,False,True,True,False,True,False,False,1.3,141,156,3.9,58,False,live\r\n28,female,False,False,True,True,True,True,True,False,False,False,False,1.6,44,123,4,46,False,live\r\n44,female,False,False,True,True,False,True,False,True,False,False,True,0.9,135,55,,41,True,die\r\n30,female,True,False,True,True,True,True,True,False,True,True,True,2.5,165,64,2.8,,True,die\r\n38,female,False,False,True,True,True,True,True,False,True,True,True,1.2,118,16,2.8,,True,die\r\n38,female,False,False,True,True,True,False,True,False,False,False,False,0.6,76,18,4.4,84,True,live\r\n50,male,False,False,True,False,False,False,True,True,True,False,False,0.9,230,117,3.4,41,True,live\r\n42,female,False,False,True,True,True,True,False,True,True,False,True,4.6,,55,3.3,,True,die\r\n33,female,True,False,False,False,False,,,False,False,False,False,1,,60,4,,True,live\r\n52,female,False,False,False,False,False,True,False,False,False,False,False,1.5,,69,2.9,,True,live\r\n59,female,False,False,True,True,False,True,True,True,True,False,False,1.5,107,157,3.6,38,True,die\r\n40,female,False,True,True,True,True,False,True,False,False,False,False,0.6,40,69,4.2,67,True,live\r\n30,female,False,False,True,True,False,True,True,False,True,False,False,0.8,147,128,3.9,100,True,live\r\n44,female,False,False,True,True,False,False,True,False,True,False,False,3,114,65,3.5,,True,live\r\n47,female,True,False,False,False,False,True,False,False,True,False,True,2,84,23,4.2,66,True,die\r\n60,female,False,False,True,False,False,False,True,True,True,False,False,,,40,,,True,live\r\n48,female,False,False,True,True,False,True,True,False,True,True,True,4.8,123,157,2.7,31,True,die\r\n22,female,True,False,False,False,False,True,False,False,False,False,False,0.7,,24,,,True,live\r\n27,female,False,False,True,False,False,True,True,False,False,False,False,2.4,168,227,3,66,True,live\r\n51,female,False,False,True,True,True,True,True,True,True,False,True,4.6,215,269,3.9,51,True,live\r\n47,female,True,False,True,True,False,True,True,False,False,True,True,1.7,86,20,2.1,46,True,die\r\n25,female,True,False,False,False,False,True,False,False,False,False,False,0.6,,34,6.4,,True,live\r\n35,female,False,False,True,False,False,,,True,True,True,False,1.5,138,58,2.6,,True,die\r\n45,female,False,False,True,True,True,True,False,False,False,False,False,2.3,,648,,,True,live\r\n54,female,False,True,False,False,False,False,True,False,False,False,False,1,155,225,3.6,67,True,live\r\n33,female,False,False,True,True,False,True,False,False,False,True,False,0.7,63,80,3,31,True,die\r\n7,female,True,False,False,False,False,True,True,True,False,False,False,0.7,256,25,4.2,,True,live\r\n42,female,False,True,True,True,False,True,False,False,True,False,False,0.5,62,68,3.8,29,True,die\r\n52,female,False,False,True,False,False,True,False,False,False,False,False,1,85,30,4,,True,live\r\n45,female,False,False,True,False,False,True,True,True,False,False,False,1.2,81,65,3,,False,live\r\n36,female,False,False,False,False,False,True,False,False,False,False,False,1.1,141,75,3.3,,True,live\r\n69,male,True,False,True,False,False,True,False,False,False,False,False,3.2,119,136,,,True,live\r\n24,female,False,False,True,False,False,True,False,False,False,False,False,1,,34,4.1,,True,live\r\n50,female,True,False,False,False,False,True,False,False,False,False,False,1,139,81,3.9,62,True,live\r\n61,female,False,False,True,True,False,,,False,True,False,False,,,,,,True,die\r\n54,female,True,False,True,False,False,False,True,False,False,False,False,3.2,85,28,3.8,,True,live\r\n56,female,False,False,True,True,True,False,True,False,True,False,False,2.9,90,153,4,,True,die\r\n20,female,False,False,True,True,True,True,False,False,True,True,False,1,160,118,2.9,23,True,live\r\n42,female,True,False,False,False,False,True,False,True,False,False,False,1.5,85,40,,,True,live\r\n37,female,False,False,True,False,False,True,False,False,True,False,False,0.9,,231,4.3,,True,live\r\n50,female,True,False,False,False,False,True,True,True,True,False,False,1,85,75,4,72,True,live\r\n34,male,True,False,True,True,True,False,True,False,True,False,False,0.7,70,24,4.1,100,True,live\r\n28,female,True,False,True,True,True,,,False,True,True,False,1,,20,4,,True,live\r\n50,female,True,False,True,False,False,True,True,True,False,True,True,2.8,155,75,2.4,32,True,die\r\n54,female,False,False,True,True,False,True,False,False,False,True,False,1.2,85,92,3.1,66,True,live\r\n57,female,False,False,True,True,False,True,False,False,True,True,False,4.6,82,55,3.3,30,True,die\r\n54,female,True,False,False,False,False,True,False,False,False,False,False,1,85,30,4.5,0,True,live\r\n31,female,False,False,True,True,True,True,False,True,False,False,False,8,,101,2.2,,True,die\r\n48,female,True,False,True,True,True,True,True,False,True,False,False,2,158,278,3.8,,True,live\r\n72,female,True,True,True,False,False,True,True,False,False,False,False,1,115,52,3.4,50,True,live\r\n38,female,False,False,False,False,False,True,True,False,False,False,False,0.4,243,49,3.8,90,True,die\r\n25,female,True,False,True,False,False,False,True,True,True,True,True,1.3,181,181,4.5,57,True,live\r\n51,female,True,False,False,False,False,False,True,False,True,False,False,0.8,,33,4.5,,True,live\r\n38,female,True,False,False,False,False,True,True,False,True,False,True,1.6,130,140,3.5,56,True,live\r\n47,female,True,False,True,True,False,True,True,False,True,True,True,1,166,30,2.6,31,True,die\r\n45,female,True,True,False,False,False,True,False,False,False,False,False,1.3,85,44,4.2,85,True,live\r\n36,female,False,False,True,True,True,False,True,False,True,False,True,1.7,295,60,2.7,,True,live\r\n54,female,False,False,True,True,False,,,True,False,True,False,3.9,120,28,3.5,43,True,die\r\n51,female,True,False,True,False,False,True,True,True,True,False,True,1,,20,3,63,True,live\r\n49,female,False,False,True,True,False,True,False,True,True,False,False,1.4,85,70,3.5,35,True,die\r\n45,female,True,False,True,True,True,True,False,False,True,True,False,1.9,,114,2.4,,True,die\r\n31,female,False,False,True,False,False,True,False,False,False,False,False,1.2,75,173,4.2,54,True,live\r\n41,female,True,False,True,False,False,True,True,True,True,False,True,4.2,65,120,3.4,,True,die\r\n70,female,False,False,True,True,True,,,,,,,1.7,109,528,2.8,35,True,die\r\n20,female,False,False,False,False,False,True,,False,False,False,False,0.9,89,152,4,,True,live\r\n36,female,True,False,False,False,False,True,False,False,False,False,False,0.6,120,30,4,,True,live\r\n46,female,True,False,True,True,True,True,False,False,True,True,True,7.6,,242,3.3,50,True,die\r\n44,female,True,False,True,False,False,True,True,False,False,False,False,0.9,126,142,4.3,,True,live\r\n61,female,False,False,True,True,False,False,True,False,True,False,False,0.8,75,20,4.1,,True,live\r\n53,male,False,False,True,False,False,True,False,True,True,False,True,1.5,81,19,4.1,48,True,live\r\n43,female,True,False,True,False,False,True,False,True,True,True,False,1.2,100,19,3.1,42,True,die\r\n'}

In [ ]:
df = pd.read_csv('hepatitis.csv')
df.head()

   age     sex steroid  antivirals  ... albumin protime histology class
0   30    male   False       False  ...     4.0     NaN     False  live
1   50  female   False       False  ...     3.5     NaN     False  live
2   78  female    True       False  ...     4.0     NaN     False  live
3   31  female     NaN        True  ...     4.0    80.0     False  live
4   34  female    True       False  ...     4.0     NaN     False  live

[5 rows x 20 columns]

# **Missing Data**

In [ ]:
df[df['spiders'].isna()]     # to detect missing values

     age     sex steroid  antivirals  ... albumin protime histology class
41    23  female    True       False  ...     4.6     NaN     False  live
56    34  female   False       False  ...     NaN     NaN     False  live
72    51  female    True       False  ...     4.4     NaN     False  live
83    67    male   False       False  ...     2.9     NaN     False  live
147   70  female   False       False  ...     2.8    35.0      True   die

[5 rows x 20 columns]

In [ ]:
df.isna().sum()   #returns no of missing values there are for each column

age                 0
sex                 0
steroid             1
antivirals          0
fatigue             1
malaise             1
anorexia            1
liver_big          10
liver_firm         11
spleen_palpable     5
spiders             5
ascites             5
varices             5
bilirubin           6
alk_phosphate      29
sgot                4
albumin            16
protime            67
histology           0
class               0
dtype: int64

In [ ]:
dropdf=df.dropna()    #Drop rows with missing values
dropdf.isna().sum()

age                0
sex                0
steroid            0
antivirals         0
fatigue            0
malaise            0
anorexia           0
liver_big          0
liver_firm         0
spleen_palpable    0
spiders            0
ascites            0
varices            0
bilirubin          0
alk_phosphate      0
sgot               0
albumin            0
protime            0
histology          0
class              0
dtype: int64

In [ ]:
print("Original dataset shape : ",df.shape)
print("After removing missing values, dataset shape is : ",dropdf.shape)

Original dataset shape :  (155, 20)
After removing missing values, dataset shape is :  (80, 20)

In [ ]:
df.dropna(subset=['spiders'],inplace=True)
print("After removing...., dataset shape is : ",df.shape) # only missing rows related to the column spiders are considered

After removing...., dataset shape is :  (150, 20)

In [ ]:
df['age'].fillna(df['age'].mean())    #fillna fun replaces all NaN values with the value passed as argument
df.isna().sum()

age                 0
sex                 0
steroid             1
antivirals          0
fatigue             0
malaise             0
anorexia            0
liver_big           6
liver_firm          7
spleen_palpable     0
spiders             0
ascites             0
varices             0
bilirubin           5
alk_phosphate      28
sgot                3
albumin            15
protime            63
histology           0
class               0
dtype: int64

# **Encoding categorical data**

In [ ]:
df.head()

   age     sex steroid  antivirals  ... albumin protime histology class
0   30    male   False       False  ...     4.0     NaN     False  live
1   50  female   False       False  ...     3.5     NaN     False  live
2   78  female    True       False  ...     4.0     NaN     False  live
3   31  female     NaN        True  ...     4.0    80.0     False  live
4   34  female    True       False  ...     4.0     NaN     False  live

[5 rows x 20 columns]

In [ ]:
df1 = df.iloc[:, :-1]   
from sklearn.preprocessing import LabelEncoder    #Label Encoding
l1 = LabelEncoder()
l1.fit(df['sex'])
df1.sex = l1.transform(df1.sex)
df1

     age  sex steroid  antivirals  ...   sgot albumin protime histology
0     30    1   False       False  ...   18.0     4.0     NaN     False
1     50    0   False       False  ...   42.0     3.5     NaN     False
2     78    0    True       False  ...   32.0     4.0     NaN     False
3     31    0     NaN        True  ...   52.0     4.0    80.0     False
4     34    0    True       False  ...  200.0     4.0     NaN     False
..   ...  ...     ...         ...  ...    ...     ...     ...       ...
150   46    0    True       False  ...  242.0     3.3    50.0      True
151   44    0    True       False  ...  142.0     4.3     NaN      True
152   61    0   False       False  ...   20.0     4.1     NaN      True
153   53    1   False       False  ...   19.0     4.1    48.0      True
154   43    0    True       False  ...   19.0     3.1    42.0      True

[150 rows x 19 columns]

In [ ]:
df1 = df.iloc[:, :-1]   
df1.isna().sum()

age                 0
sex                 0
steroid             1
antivirals          0
fatigue             0
malaise             0
anorexia            0
liver_big           6
liver_firm          7
spleen_palpable     0
spiders             0
ascites             0
varices             0
bilirubin           5
alk_phosphate      28
sgot                3
albumin            15
protime            63
histology           0
dtype: int64

In [ ]:
df1 = df.iloc[:, :-1]   
ddf=pd.get_dummies(data=df1)              #one hot encoding
ddf                                       #1.DataFrame.get_dummies

     age  antivirals  bilirubin  ...  ascites_True  varices_False  varices_True
0     30       False        1.0  ...             0              1             0
1     50       False        0.9  ...             0              1             0
2     78       False        0.7  ...             0              1             0
3     31        True        0.7  ...             0              1             0
4     34       False        1.0  ...             0              1             0
..   ...         ...        ...  ...           ...            ...           ...
150   46       False        7.6  ...             1              0             1
151   44       False        0.9  ...             0              1             0
152   61       False        0.8  ...             0              1             0
153   53       False        1.5  ...             0              0             1
154   43       False        1.2  ...             1              1             0

[150 rows x 30 columns]

In [ ]:
#2Using OneHotEncoder from Sci-Kit Learn
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
df1 = df.iloc[: :-1]
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = pd.DataFrame(ct.fit_transform(df1))