In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving HR.csv to HR.csv

In [ ]:
df = pd.read_csv("HR.csv")
print(df)

      Emp ID Name Prefix First Name  ...     Region  User Name         Password
0     526540         Ms.  Angelique  ...  Northeast  akgoodwin       z{d>ez%{.@
1     859327         Ms.       Jeni  ...      South  jsshaffer         7U56!*!O
2     887387         Ms.     Donald  ...      South   dtfarris    rX.F{j&]&m&&X
3     779497        Hon.     Steven  ...    Midwest   sdrendon      a+2;sx}<G]y
4     896517        Drs.     Jenell  ...    Midwest  jlalmanza         Ou7RX{yT
...      ...         ...        ...  ...        ...        ...              ...
4995  488800         Mr.    Roberto  ...  Northeast   rrharter         b>|V#Ywx
4996  428330        Hon.    Brittni  ...      South      bbcyr  We/b$tUwvstNmE2
4997  313027         Mr.     Gerald  ...    Midwest  gjbeaudry         hAw[]_s-
4998  826852        Mrs.     Emilee  ...    Midwest    edemery       jj0uKCopdM
4999  948300         Ms.   Larhonda  ...       West   lgdozier        we_Uppg02

[5000 rows x 37 columns]

In [ ]:
df.columns

Index(['Emp ID', 'Name Prefix', 'First Name', 'Middle Initial', 'Last Name',
       'Gender', 'E Mail', 'Father's Name', 'Mother's Name',
       'Mother's Maiden Name', 'Date of Birth', 'Time of Birth', 'Age in Yrs.',
       'Weight in Kgs.', 'Date of Joining', 'Quarter of Joining',
       'Half of Joining', 'Year of Joining', 'Month of Joining',
       'Month Name of Joining', 'Short Month', 'Day of Joining',
       'DOW of Joining', 'Short DOW', 'Age in Company (Years)', 'Salary',
       'Last % Hike', 'SSN', 'Phone No. ', 'Place Name', 'County', 'City',
       'State', 'Zip', 'Region', 'User Name', 'Password'],
      dtype='object')

In [ ]:
df.dtypes

Emp ID                      int64
Name Prefix                object
First Name                 object
Middle Initial             object
Last Name                  object
Gender                     object
E Mail                     object
Father's Name              object
Mother's Name              object
Mother's Maiden Name       object
Date of Birth              object
Time of Birth              object
Age in Yrs.               float64
Weight in Kgs.              int64
Date of Joining            object
Quarter of Joining         object
Half of Joining            object
Year of Joining             int64
Month of Joining            int64
Month Name of Joining      object
Short Month                object
Day of Joining              int64
DOW of Joining             object
Short DOW                  object
Age in Company (Years)    float64
Salary                      int64
Last % Hike                object
SSN                        object
Phone No.                  object
Place Name                 object
County                     object
City                       object
State                      object
Zip                         int64
Region                     object
User Name                  object
Password                   object
dtype: object

In [ ]:
df.to_excel("output.xlsx")

# **Selecting particular rows or columns from data set**

In [ ]:
df.head(10) #default first 5

   Emp ID Name Prefix First Name  ...     Region   User Name       Password
0  526540         Ms.  Angelique  ...  Northeast   akgoodwin     z{d>ez%{.@
1  859327         Ms.       Jeni  ...      South   jsshaffer       7U56!*!O
2  887387         Ms.     Donald  ...      South    dtfarris  rX.F{j&]&m&&X
3  779497        Hon.     Steven  ...    Midwest    sdrendon    a+2;sx}<G]y
4  896517        Drs.     Jenell  ...    Midwest   jlalmanza       Ou7RX{yT
5  220965        Mrs.     Almeta  ...      South  aybrookins     HQHKE_+9hv
6  721091       Prof.     Bobbie  ...    Midwest   bebranson   tA5zrwtY9\!Y
7  633636       Prof.    Bertram  ...  Northeast  brcarlisle    F4G46Phi$qF
8  823898       Prof.    Carlton  ...    Midwest   celeclair     Kce]/Rnti6
9  413865         Mr.       Todd  ...    Midwest    trslater       EZ5}EHI4

[10 rows x 37 columns]

In [ ]:
df.tail(10)   #default last 5

      Emp ID Name Prefix First Name  ...     Region  User Name         Password
4990  530622        Drs.        Dee  ...    Midwest     dvoden       70r<+nL7-$
4991  824401         Mr.   Faustino  ...    Midwest  fwhackney      yJWyQ]m*M/I
4992  949086         Mr.       Joey  ...      South  juburrell  Xf*#UA_d*Lz~YwA
4993  168076         Mr.      Romeo  ...       West  rzgoodwin     lpVkCgur~ziz
4994  343083        Hon.     Tressa  ...      South  ttbrinson   dzOya!Y{cU%]E~
4995  488800         Mr.    Roberto  ...  Northeast   rrharter         b>|V#Ywx
4996  428330        Hon.    Brittni  ...      South      bbcyr  We/b$tUwvstNmE2
4997  313027         Mr.     Gerald  ...    Midwest  gjbeaudry         hAw[]_s-
4998  826852        Mrs.     Emilee  ...    Midwest    edemery       jj0uKCopdM
4999  948300         Ms.   Larhonda  ...       West   lgdozier        we_Uppg02

[10 rows x 37 columns]

In [ ]:
df.rename(columns={"Emp ID":"Emp_id","E Mail":"E_mail"},inplace=True)

In [ ]:
df["Emp_id"]     #Particular column

0       526540
1       859327
2       887387
3       779497
4       896517
         ...
4995    488800
4996    428330
4997    313027
4998    826852
4999    948300
Name: Emp_id, Length: 5000, dtype: int64

In [ ]:
df[["Emp_id","Salary","E_mail"]].head(10)      #Particular columns

   Emp_id  Salary                       E_mail
0  526540  193710  angelique.goodwin@gmail.com
1  859327  144133       jeni.shaffer@gmail.com
2  887387  132617  donald.farris@bellsouth.net
3  779497   77898      steven.rendon@gmail.com
4  896517  139856     jenell.almanza@yahoo.com
5  220965   90576    almeta.brookins@gmail.com
6  721091  178641   bobbie.branson@hotmail.com
7  633636  163773     bertram.carlisle@aol.com
8  823898   50397      carlton.leclair@cox.net
9  413865   54458    todd.slater@earthlink.net

In [ ]:
df.loc[0:5,["Emp_id","Salary","E_mail"]]    #selecting only specific columns and rows

   Emp_id  Salary                       E_mail
0  526540  193710  angelique.goodwin@gmail.com
1  859327  144133       jeni.shaffer@gmail.com
2  887387  132617  donald.farris@bellsouth.net
3  779497   77898      steven.rendon@gmail.com
4  896517  139856     jenell.almanza@yahoo.com
5  220965   90576    almeta.brookins@gmail.com

In [ ]:
df.loc[0:10,"Emp_id":"E_mail"]   #selecting all columns from Emp ID to E Mail & 0-10 rows

    Emp_id Name Prefix First Name  ... Last Name Gender                       E_mail
0   526540         Ms.  Angelique  ...   Goodwin      F  angelique.goodwin@gmail.com
1   859327         Ms.       Jeni  ...   Shaffer      F       jeni.shaffer@gmail.com
2   887387         Ms.     Donald  ...    Farris      F  donald.farris@bellsouth.net
3   779497        Hon.     Steven  ...    Rendon      M      steven.rendon@gmail.com
4   896517        Drs.     Jenell  ...   Almanza      F     jenell.almanza@yahoo.com
5   220965        Mrs.     Almeta  ...  Brookins      F    almeta.brookins@gmail.com
6   721091       Prof.     Bobbie  ...   Branson      M   bobbie.branson@hotmail.com
7   633636       Prof.    Bertram  ...  Carlisle      M     bertram.carlisle@aol.com
8   823898       Prof.    Carlton  ...   Leclair      M      carlton.leclair@cox.net
9   413865         Mr.       Todd  ...    Slater      M    todd.slater@earthlink.net
10  439483         Mr.  Adalberto  ...     Hazel      M  adalberto.hazel@yahoo.co.in

[11 rows x 7 columns]

In [ ]:
df.columns

Index(['Emp_id', 'Name Prefix', 'First Name', 'Middle Initial', 'Last Name',
       'Gender', 'E_mail', 'Father's Name', 'Mother's Name',
       'Mother's Maiden Name', 'Date of Birth', 'Time of Birth', 'Age in Yrs.',
       'Weight in Kgs.', 'Date of Joining', 'Quarter of Joining',
       'Half of Joining', 'Year of Joining', 'Month of Joining',
       'Month Name of Joining', 'Short Month', 'Day of Joining',
       'DOW of Joining', 'Short DOW', 'Age in Company (Years)', 'Salary',
       'Last % Hike', 'SSN', 'Phone No. ', 'Place Name', 'County', 'City',
       'State', 'Zip', 'Region', 'User Name', 'Password'],
      dtype='object')

In [ ]:
df.shape

(5000, 37)

In [ ]:
df.Gender.unique()

array(['F', 'M'], dtype=object)

In [ ]:
df.index.nunique()

5000

#**Arranging data in ascending or descending order**

In [ ]:
df.sort_values("Emp_id")

      Emp_id Name Prefix First Name  ...     Region    User Name        Password
3563  111150        Drs.   Sanjuana  ...    Midwest    sesaddler        9X86]CTj
4632  111500        Hon.    Jarrett  ...    Midwest      jmyanez     K|^5$R1@5bO
1431  111692         Dr.       Emil  ...       West     eqparris        y}axOm>z
3221  112574         Dr.    Raleigh  ...       West     roosorio    M6zTzQTaShxE
3157  112680         Mr.        Ira  ...      South     ivnathan     O|VC]y_3a/.
...      ...         ...        ...  ...        ...          ...             ...
652   998903        Mrs.    Chasity  ...    Midwest      chguido  b*4&3d8Aouc:D9
378   999307         Mr.      Daryl  ...      South  dctreadwell     8Wq?HZS[MhF
3666  999422        Hon.     Lorrie  ...  Northeast      lvbaber      r1C\~kk]Uu
4387  999496         Mr.      Bryan  ...      South      bxburks     8D9jX1-9R+^
4736  999800        Mrs.    Yolando  ...      South  ywstillwell    ht3-VRL-5|%{

[5000 rows x 37 columns]

In [ ]:
df.sort_values("Emp_id",ascending=False)

      Emp_id Name Prefix First Name  ...     Region    User Name        Password
4736  999800        Mrs.    Yolando  ...      South  ywstillwell    ht3-VRL-5|%{
4387  999496         Mr.      Bryan  ...      South      bxburks     8D9jX1-9R+^
3666  999422        Hon.     Lorrie  ...  Northeast      lvbaber      r1C\~kk]Uu
378   999307         Mr.      Daryl  ...      South  dctreadwell     8Wq?HZS[MhF
652   998903        Mrs.    Chasity  ...    Midwest      chguido  b*4&3d8Aouc:D9
...      ...         ...        ...  ...        ...          ...             ...
3157  112680         Mr.        Ira  ...      South     ivnathan     O|VC]y_3a/.
3221  112574         Dr.    Raleigh  ...       West     roosorio    M6zTzQTaShxE
1431  111692         Dr.       Emil  ...       West     eqparris        y}axOm>z
4632  111500        Hon.    Jarrett  ...    Midwest      jmyanez     K|^5$R1@5bO
3563  111150        Drs.   Sanjuana  ...    Midwest    sesaddler        9X86]CTj

[5000 rows x 37 columns]

In [ ]:
print(df)

In [ ]:
df["Salary"].describe()

count      5000.000000
mean     119986.614800
std       46434.151143
min       40011.000000
25%       79153.000000
50%      120234.000000
75%      160227.500000
max      199968.000000
Name: Salary, dtype: float64

In [ ]:
df.describe(include = ['int64'])

            Emp_id  Weight in Kgs.  ...         Salary           Zip
count    5000.0000     5000.000000  ...    5000.000000   5000.000000
mean   555385.4624       59.968200  ...  119986.614800  50226.964200
std    256301.1832       13.647082  ...   46434.151143  27579.386224
min    111150.0000       40.000000  ...   40011.000000    211.000000
25%    335512.5000       50.000000  ...   79153.000000  27319.250000
50%    555986.0000       57.000000  ...  120234.000000  49379.500000
75%    781261.2500       70.000000  ...  160227.500000  73444.000000
max    999800.0000       90.000000  ...  199968.000000  99919.000000

[8 rows x 7 columns]

In [ ]:
df.agg(["mean","median","min","max"])

             Emp_id Name Prefix First Name  ...   Region  User Name       Password
mean    555385.4624         NaN        NaN  ...      NaN        NaN            NaN
median  555986.0000         NaN        NaN  ...      NaN        NaN            NaN
min     111150.0000         Dr.      Aaron  ...  Midwest   aabeeler     0!JkW432%v
max     999800.0000       Prof.      Zulma  ...     West  zyrawlins  z~w/>c+;4wFNG

[4 rows x 37 columns]

In [ ]:
df.rename(columns={"County":"Country"},inplace=True)
df["Country"].value_counts()

Los Angeles    71
Jefferson      66
Montgomery     47
Washington     44
Jackson        42
               ..
Hesperia        1
Spangle         1
Rawlins         1
Pontotoc        1
Hollybush       1
Name: Country, Length: 1381, dtype: int64

# **Filtering data based on some conditions**

In [ ]:
df[(df['Salary']>199000) & (df['Age in Yrs.']>40)]

      Emp_id Name Prefix First Name  ...   Region   User Name         Password
256   552215         Mr.       Rick  ...  Midwest    rdbedard       a*j7_Ama_1
345   776039        Mrs.     Nancey  ...     West      npbond    V|jm3X_i]>Xn;
588   703258         Ms.       Lacy  ...    South   locamacho   uu>y!4dS3D/p?7
789   258062         Mr.     Erasmo  ...  Midwest   eialmeida         m<f<g.*6
1017  692171        Hon.    Marquis  ...    South      mdyoon  f9\1GeYcXQV2YB#
1273  935891         Mr.      Jarod  ...  Midwest  jalankford  W1@oUG$.2kYD]z2
2194  597583        Mrs.        Joi  ...     West   jkhoskins     GFLHrrWB7fqa
2993  783435        Mrs.    Brandee  ...    South     bethorn      XJ0cmCm<~rX
3531  120168        Mrs.     Maryam  ...  Midwest  mbgriffith       a{[Q*X#AzH
4381  253932        Drs.      Missy  ...    South     malaney      JC~P^rf>JAm

[10 rows x 37 columns]

In [ ]:
df.loc[(df.Salary>120000) & (df.Gender=='M')][0:10]

    Emp_id Name Prefix First Name  ...     Region     User Name         Password
6   721091       Prof.     Bobbie  ...    Midwest     bebranson     tA5zrwtY9\!Y
7   633636       Prof.    Bertram  ...  Northeast    brcarlisle      F4G46Phi$qF
10  439483         Mr.  Adalberto  ...    Midwest       akhazel  j8v|]L6g2j/T$4+
12  748190         Mr.    Vicente  ...    Midwest     vddawkins  t\XA;6?;[c>!47c
13  397283         Mr.        Rex  ...  Northeast          rqng   rcT|A/ba:8aZ$q
15  495667         Mr.       Cory  ...       West      chclarke        k2QH6T#d!
17  537591         Dr.     Samuel  ...      South       sgwendt  pOq-woq:}4.ubd0
18  909018         Mr.     Virgil  ...      South  vrtrowbridge  3PE>x:gOp<AY5jN
24  500905        Hon.     Harris  ...      South     hzbeavers         gv8q[B?p
34  900756         Mr.   Benjamin  ...      South        bodoss         3k}8*JZ!

[10 rows x 37 columns]

In [ ]:
df.groupby('Salary').min()

        Emp_id Name Prefix First Name  ...     Region   User Name         Password
Salary                                 ...
40011   970409         Ms.     Mertie  ...       West   mjbinkley      ZRDsWf20:fB
40049   392276        Drs.      Kathe  ...  Northeast     kqacker  702mSZ|Q2eRLQ7p
40105   785085         Mr.      Britt  ...  Northeast   bdcarrion      H9O~D*mQ>0h
40135   179349         Ms.      Ettie  ...    Midwest    epkellum     G|W~?[.-S2o>
40152   802411         Ms.    Aracely  ...      South     adashby       SXZ|;]]+\]
...        ...         ...        ...  ...        ...         ...              ...
199844  521177         Mr.       Ryan  ...      South    rvcleary  t4GNt:K<;d<]vKn
199908  935891         Mr.      Jarod  ...    Midwest  jalankford  W1@oUG$.2kYD]z2
199909  253932        Drs.      Missy  ...      South     malaney      JC~P^rf>JAm
199958  232124         Ms.     Season  ...  Northeast      sishea       n|/d5vXfnG
199968  581520        Hon.     Emmitt  ...    Midwest  ejmontague        eudbJ\d$A

[4917 rows x 36 columns]

# **Merging and concatenating two datasets**

In [ ]:
df1 = pd.DataFrame(df, columns= ["Emp_id",'Gender',"E_mail","Salary","Country"])
df2 = pd.DataFrame(df, columns= ["Emp_id", 'First Name', 'Middle Initial', 'Last Name',])
df3 = pd.concat([df2,df1],axis=1)
print(df3)
df3.columns

      Emp_id First Name  ...  Salary    Country
0     526540  Angelique  ...  193710     Monroe
1     859327       Jeni  ...  144133   Crenshaw
2     887387     Donald  ...  132617   Franklin
3     779497     Steven  ...   77898  Champaign
4     896517     Jenell  ...  139856    Carroll
...      ...        ...  ...     ...        ...
4995  488800    Roberto  ...   87448   New York
4996  428330    Brittni  ...  189958       Wake
4997  313027     Gerald  ...  184022     Burney
4998  826852     Emilee  ...  127052       Dane
4999  948300   Larhonda  ...  112287    Spokane

[5000 rows x 9 columns]

Index(['Emp_id', 'First Name', 'Middle Initial', 'Last Name', 'Emp_id',
       'Gender', 'E_mail', 'Salary', 'Country'],
      dtype='object')

In [ ]:
df3 = pd.merge(df1,df2,on="Emp_id")
print(df3)
df3.columns

      Emp_id Gender  ... Middle Initial  Last Name
0     526540      F  ...              K    Goodwin
1     859327      F  ...              S    Shaffer
2     887387      F  ...              T     Farris
3     779497      M  ...              D     Rendon
4     896517      F  ...              L    Almanza
...      ...    ...  ...            ...        ...
5029  488800      M  ...              R     Harter
5030  428330      F  ...              B        Cyr
5031  313027      M  ...              J    Beaudry
5032  826852      F  ...              D      Emery
5033  948300      F  ...              G     Dozier

[5034 rows x 8 columns]

Index(['Emp_id', 'Gender', 'E_mail', 'Salary', 'Country', 'First Name',
       'Middle Initial', 'Last Name'],
      dtype='object')

# **Writing or Exporting data in CSV or Excel format**

In [105]:
df3.to_csv('Merge.csv')

# **Iterating over the rows of dataset**

In [79]:
for i in df.index:
  print(df["First Name"][i], df["Emp_id"][i])

Streaming output truncated to the last 5000 lines.
Angelique 526540
Jeni 859327
Donald 887387
Steven 779497
Jenell 896517
Almeta 220965
Bobbie 721091
Bertram 633636
Carlton 823898
Todd 413865
Adalberto 439483
Seymour 809408
Vicente 748190
Rex 397283
Arlena 553684
Cory 495667
Sofia 936158
Samuel 537591
Virgil 909018
Elda 878666
Robert 995710
Humberto 511059
Anastasia 754455
Collene 489275
Harris 500905
Kathe 984409
Ashly 812053
Geraldo 550206
Leigh 728053
Devon 184257
Yevette 235295
Irena 767674
Cory 391837
Dolores 466560
Benjamin 900756
Theron 678628
Hilton 492527
Sixta 886060
Sade 366431
Shemika 331297
Winfred 496541
Rogelio 654617
Damion 163409
Dannie 299088
Stephan 961442
Dorian 155097
Jake 976422
Claudio 138911
Marcel 160938
Dillon 399707
Sammy 713294
Sterling 627298
Ivonne 709884
Clair 932773
Jenni 796605
Tayna 885395
Vern 411503
Harrison 622405
Preston 233136
Aleen 170637
Brent 215719
Adalberto 452163
Rafael 572204
Aurea 779517
Ramiro 844157
Celine 312726
Bryant 419549
Oswaldo 505927
Kacy 526254
Brock 460226
Ramiro 840113
Myron 432820
Freeman 957596
Mathew 530134
Alexander 316372
Renee 501658
Tommie 147133
Michale 551149
Denisha 595558
Napoleon 637407
Tonya 597741
Clement 403534
Charles 314661
Chastity 317987
Verna 820109
Alfred 388558
Michal 403207
Wenona 143711
Allan 402180
Nam 242388
Yolande 819367
Whitney 962291
Terence 856379
Alberto 149972
Jacqueline 174955
Clemente 549389
Chang 466832
Marvin 203380
Eldora 915991
Azzie 289172
Titus 914365
Shantell 971242
Cameron 503248
Virgilio 521540
Eboni 790395
Ward 734861
Yasuko 592815
Agustin 556008
Sunny 888597
Janyce 946550
Bernardo 438869
Leon 685600
Walker 829901
Rolando 354626
Glenn 296454
Tandy 867400
Irving 354161
Elin 906193
William 602041
Silvana 514224
Kirby 834046
Rubin 538803
Lee 487412
Jesus 286281
Riley 788924
Nova 416576
Shandra 960215
Jacquie 549513
Nelle 509864
Rich 832966
Antoine 306746
Blaine 945031
Raymundo 684637
Blair 891328
Charley 383614
Heath 180789
Zack 356050
Zaida 185465
Porfirio 687184
Ryan 489916
Luther 435833
Deon 702411
Dana 645244
Manual 755710
Kenton 329638
Julian 947428
Deon 353117
Angela 525537
Heidi 117598
Gayle 957898
Janey 643106
Emilio 691376
Brinda 290435
Alexander 428318
Frank 709493
Monty 837051
Brinda 818907
Benny 613084
Monty 400205
Lester 363221
Shellie 445473
Kerrie 229262
Gerard 952927
Parker 723502
Riva 642626
Steve 470485
Fleta 620100
Chung 771679
Frieda 904561
Sirena 465279
Alisha 293923
Deedee 331158
Cecile 483286
Roosevelt 957621
Floyd 464683
Lacey 431073
Larry 346953
Joel 209718
Camilla 179094
Tyron 209065
Joey 915973
Hubert 793674
Jason 665291
Raymond 258503
Carmen 910235
Daisy 605376
Archie 291167
Bryan 864600
Shae 862997
Bertha 989496
Rick 411593
Lon 462737
Linnie 634772
Terica 864491
Jae 771200
Jame 541253
Larisa 704999
Delsie 847603
Janna 462706
Harvey 988654
Muriel 130373
Emelina 490970
Nida 885253
Margareta 996402
Michelle 947623
Ferdinand 184402
Muoi 924964
Yasuko 183909
Christopher 354069
Scott 613719
Johnathon 357718
Scarlett 834650
Ta 888177
Nathanial 663522
Jamel 807484
Gracia 576715
Sheri 387891
Heriberto 875533
Ellsworth 704654
Waldo 396706
Isreal 837859
Leana 906924
Boyd 244379
Les 431394
Daren 549982
Tyler 766429
Russel 344898
Johnnie 426061
Gaylene 788422
Chi 494903
Erich 939209
Gladis 415047
Karly 172373
Lise 956982
Bong 377842
Sherika 735648
Geraldo 856621
Shakita 410532
Patrice 387199
Marvis 486442
Sherrie 712096
Wilhemina 187207
Rosario 583435
Ned 652292
Mabel 839764
Lucilla 817441
Modesta 319686
Kenneth 340456
Shara 862292
Ethyl 155455
Ozie 755512
Apryl 350036
Dorsey 660160
Theo 615367
Tracy 926340
Alberto 741414
Rick 552215
Jake 629523
Giuseppina 257355
Adolfo 405704
Majorie 809563
Lela 551274
Everett 410721
Nestor 411970
Clarice 502786
Humberto 779981
Fredrick 243913
Amira 465563
Tonda 126947
Sal 997123
Melissa 768053
Rocio 922004
Margaret 893257
Mahalia 513516
Eliz 550688
Irving 578658
Rich 687401
Elden 616542
Cameron 229674
Bert 910839
Mittie 916771
Lupe 917366
Darren 138184
Jamaal 752368
Roger 246567
Timika 364826
Lazaro 818588
Latasha 976130
Felton 113693
Jeff 259326
Peter 203015
Alesia 507960
Enedina 685086
Wyatt 377827
Raleigh 793908
Penney 562756
Homer 593831
Catrice 654413
Elisha 177908
Rufus 213923
Efrain 453046
Cliff 416395
Hal 428638
Elena 185040
Frederick 369773
Laurena 509313
Everette 842810
Londa 641526
Claudio 347756
Elliot 310825
Carissa 676338
Ammie 982306
Manuel 912439
Denice 300153
Raleigh 324892
September 742590
Harry 402636
Orval 405301
Kelle 948900
Evelia 718875
Chong 484415
Deshawn 350283
Estelle 765212
Asa 760606
Wanetta 331661
Dudley 224563
Leonel 449882
Dirk 450738
Travis 806622
Ray 385833
Craig 763163
Billi 897397
Loraine 862696
Christopher 696128
Sanford 396732
Felipa 525550
Rocky 391646
Tara 869042
Elton 265358
Rey 868673
Blair 626383
Eduardo 150291
Shaun 909677
Lanora 138191
Suellen 321519
Nancey 776039
Eusebio 121192
Lan 348481
Terry 156143
Demetrius 986792
Meaghan 567275
Pedro 441872
Adam 247716
Tomiko 707951
Joseph 749500
Roberto 302532
Peggy 554841
Glynis 341481
August 406419
Fallon 548138
Hildegarde 613380
Brenton 668685
Tomika 805231
Colby 765983
Len 383673
Garry 308543
Julius 811224
Amber 637979
Porter 431097
Mollie 509371
Gregory 290554
Edgardo 398989
Teressa 551061
Zenaida 384939
Stephani 179692
Len 628495
Kareem 394010
Raymond 372801
Daryl 999307
Sol 486707
Thomas 312646
Emmitt 581520
Jarvis 701494
Candida 617343
Shanita 653595
Fredia 248995
Ivey 739214
Patrick 939293
Latrina 382405
Rae 978581
Aracely 802411
Roxana 438290
Bernardina 375215
Gaston 419637
Annemarie 887447
Tangela 736349
Margorie 710423
Cornelius 392529
Wiley 922113
Nettie 994548
Faustino 849237
Shiela 124742
Rosaria 612842
Liz 149140
Johanne 927344
Frank 375880
Giovanni 403048
Stanton 258773
Merlin 602135
Mica 673774
Yaeko 875902
Scot 296157
Zackary 788810
Whitney 328375
America 601554
Roberto 828621
Alfred 285385
Daniele 556750
Alonzo 428798
Altha 920890
Rodrigo 619908
Maximina 608086
Eboni 887855
Ellena 593416
Gaston 453240
Ronny 333131
Humberto 704255
Lai 836272
Samatha 870724
Gayla 309197
Nelle 868288
Emory 289702
Dewitt 229399
Ethan 409602
Lala 926666
Cathie 146904
Olinda 783011
Jackie 373115
Willian 829747
Pearly 390136
Hugh 418115
Benton 595624
Willian 334312
Stephaine 693498
Kortney 612413
Roxanne 477357
Cyndy 406344
Judson 659040
Toccara 393086
Elijah 547881
Dusti 401585
Bud 275099
Jewel 295128
Tonette 368884
Maxwell 801641
Tamekia 596849
Junita 319677
Kirstie 214725
Raymon 838989
Gertha 204641
Virgilio 781241
Lieselotte 308548
Oda 788639
Sammie 773441
Kraig 710473
Booker 280616
Daron 926471
Ronnie 420058
Cruz 923618
Luella 626643
Hedwig 709787
Arvilla 605917
Mikki 203063
Osvaldo 832795
Meta 846758
Dedra 817618
Lynetta 589012
Sharice 389576
Hilton 254755
Leroy 580822
Joann 448922
Santiago 916834
Rebekah 352019
Magen 807476
Emmaline 213620
Evangelina 510975
Jonah 682658
Lloyd 920812
Joel 335636
Alisia 758862
Jacinda 986092
Barabara 647012
Carmen 358642
Lowell 640581
Rudolf 822054
Shaunta 251321
Dewayne 875792
King 432229
Xuan 306701
Marni 996381
Lawanda 376941
Gilberto 497576
Yuette 182058
Chelsie 489450
Aurelio 318089
Carl 301953
Shanna 329907
Linwood 696295
Donny 635271
Ninfa 315034
Harrison 285675
Kelley 177300
Winnifred 814002
Elias 580274
Alfonso 863434
Simone 768022
Woodrow 292052
Dario 395472
Polly 669795
Lurline 259749
Charlie 862228
Theresa 882209
Contessa 840009
Sharen 413384
Adele 408482
Ha 666407
Fletcher 218533
Nickolas 973342
Blanche 197578
Warren 669996
Erich 539579
Carisa 125872
Cruz 837426
Vanetta 235913
Fernanda 274339
Darell 512957
Elaina 235415
Jc 586433
Germaine 255982
Chara 357307
Emmett 667859
Burl 503729
Yi 637992
Carlos 809585
King 960549
Emmett 232646
Tessie 741386
Clint 184514
Lacy 447090
Forest 272372
Jin 901940
Herb 863659
Hilary 482788
Charita 390321
Teddy 984074
Tim 420425
Walter 847428
Latrina 636027
Fred 894744
Lindsey 745058
Shandi 814720
Bryce 799474
Guadalupe 430660
Emogene 502976
Quentin 443961
Manda 980544
Tosha 236627
Basil 259771
Joya 316153
Latrice 602901
Launa 319426
Santos 717322
Allan 603441
Sarai 316773
Marlin 561706
Stevie 283233
Danial 360785
Sharee 568396
Edwin 569208
Christian 862508
Bruno 595400
Xenia 391677
Sadie 629094
Dee 538099
Milo 447315
Karrie 866533
Annetta 223842
Shiloh 695913
Lacy 703258
Latricia 799440
Olin 322907
Ines 927582
Ernest 421662
Georgiann 626217
Kortney 563278
Roselee 377693
Ming 890991
Stefania 314801
Paige 207814
Cynthia 202115
Ollie 921413
Marc 156912
Bart 214684
Brandon 915227
Arlie 358685
Deandrea 893055
Palmer 195707
Ronny 848244
Linwood 264711
Sindy 504189
Reyes 930232
Rubin 163114
Kandi 653650
Gerard 114498
Hershel 879035
Jermaine 644180
Tom 228031
Kaye 338621
Kizzy 920425
Malik 378735
Ute 781527
Reita 517758
Lacy 419690
Roland 215358
Van 268404
Frieda 844671
Amparo 631876
Leida 666689
Detra 317405
Kasey 266463
Bobby 326786
Cinthia 812211
Jenny 634529
Kiana 831799
Margart 525091
Daron 978800
Weston 739146
Sook 704797
Luanna 567772
Randy 310173
Lashawnda 144548
Miss 734469
Kristopher 630016
Shawanna 780778
Aldo 538505
Buck 579723
Jacalyn 901762
Emilio 765235
Karl 186047
Kennith 389919
Billy 990488
Shelley 385559
Chasity 998903
Trevor 929869
Cathrine 435093
Henry 858385
Santo 716058
Carline 371501
Davida 330900
Valentin 508854
Cristobal 417646
Art 196640
Dale 732435
Stevie 784503
Andrea 705501
Sherrell 655342
Angelina 945089
Werner 935819
Zula 772602
Edwin 890888
Serina 927902
Florentino 919021
Jamie 361407
Maisie 175904
Ahmad 251891
Verlene 965500
Tarsha 166633
Darell 259575
Oliver 836165
Moses 484597
Julio 682475
Tristan 825983
Jong 128477
Jeane 744163
Lon 383161
Domingo 507995
Jae 508004
Sherman 662220
Ivelisse 347957
Cynthia 790041
Norbert 243683
Jody 820854
Elly 219494
Anton 355333
Leonor 674758
Hilton 591213
Jenifer 606551
Elvira 321983
Cira 280235
Leandro 814062
Clifford 375719
Brendan 812440
Shemeka 526095
Marta 480343
Muoi 387512
Mario 411827
Lucius 379192
Bridgette 745056
Criselda 343590
Marge 292943
Nannie 821131
Grant 274488
Debbra 300647
Neil 563480
Alba 695502
Parthenia 593435
Jimmy 628748
Clark 391027
Carlene 777314
Armand 987973
Refugio 414100
Norbert 128069
Jada 953557
Rick 741578
Arden 528503
Zane 992542
Alexia 292646
Marcelene 704563
Delma 698791
Maritza 526168
Johanna 891639
Oliver 641307
Sima 354053
Deneen 719451
Jina 390131
Gricelda 355249
Jaleesa 583972
Stewart 358904
Marion 706362
Benny 147225
Agustina 986041
Eusebio 929826
Clinton 995551
Bridget 607132
Rasheeda 290565
Trevor 296852
Elane 608230
Sheron 850042
Zenobia 763441
Jeanne 828962
Ida 493020
Melvin 530089
Daysi 386711
John 857807
Charity 377190
Renay 298803
Fernanda 372452
Alta 580489
Norberto 613875
Shad 707888
Krista 454442
Ara 184562
Bennett 695969
Adaline 445332
Morgan 624271
Wilson 861922
Natalya 658898
Ileen 127075
Margherita 423011
Arron 711581
Jaquelyn 927847
Mario 977563
Numbers 232875
Andrea 642447
Delbert 609424
Lucilla 176971
Freeman 124449
Rashad 720547
Laurinda 449995
Alejandro 652873
Lisandra 703906
Hiram 294025
Danyelle 682902
Herbert 649679
America 626899
Scot 118144
Carol 875693
Tera 409197
Izola 556895
Erasmo 258062
Roberto 888447
Darron 184520
Jann 234615
Lahoma 880500
Janetta 276557
Kim 253914
Annie 214151
Man 600965
Zackary 582395
Malissa 268040
Kayla 265738
Kasey 386523
Lyman 738090
Ethyl 597179
Wilbur 667427
Edison 569695
Kris 690528
Micah 345118
Latonia 163411
Michael 751229
Manuel 804129
Neil 918594
Jamie 366810
Marin 813992
Latrina 596960
Gus 930076
Eugene 606888
Dorothea 381302
Sheree 365733
Laquita 211648
Will 998499
Cristopher 275262
Young 366361
Omega 495571
Michale 400422
Loyd 641760
Christoper 216738
Jeff 983720
Dagmar 818136
Randal 186578
Rickie 299513
Frankie 361480
Tamekia 473266
Garrett 967064
Carleen 720426
Meggan 811632
Teddy 428584
Devin 961569
Jamison 488863
Sarai 694905
Efren 768563
Major 194454
Lavonna 476189
Caridad 786096
Gigi 557710
Torie 861085
Elinor 374081
Janeen 954614
Charlsie 687789
Sharie 563948
Antonio 319531
Christina 622824
Carmen 725043
Lyn 882089
Merry 964283
Siobhan 335484
Khadijah 424085
Siu 162785
Salvatore 210955
Carrie 884750
Clyde 575116
Aurelio 757652
Danyell 838027
Noelia 879616
Hugo 517817
Meggan 480982
Rubi 569298
Teodora 759808
Gary 321903
Jonathan 290293
Perry 143317
Velva 809667
Donte 523237
Kelley 633556
Normand 938396
Ulysses 283154
Lenny 304382
Carol 685306
Verona 153156
Linwood 306626
Toni 341823
Noelia 471637
Antony 431532
Darci 781612
Tracie 542082
Neville 550764
Denny 154437
Krystal 176482
Johnie 666715
Sterling 138019
Seth 842541
Adele 873670
Rochell 290646
Carlo 786408
Alexis 559051
Henrietta 516893
Clark 760501
Kelsey 511609
Ofelia 868039
Gaston 469485
Melvin 264051
Jessie 583643
Mallie 681669
Tanner 272735
Valentin 677434
Booker 985202
Earl 996307
Keneth 326436
Lillie 412382
Ashton 536653
Oma 961962
Concetta 347222
Cary 818991
Bradley 798815
Maryam 396181
Emmett 715790
Roslyn 366282
Melita 420178
Isobel 742376
Verena 490788
Tommy 600534
Renetta 373020
Alvaro 917053
Evonne 978259
Corrine 770283
Xiomara 522846
Cordell 490361
Deirdre 634421
Gonzalo 673541
Glinda 864503
Guadalupe 422206
Joe 857332
Ilda 171693
Marcos 313842
Winnifred 465030
Raymond 445222
Latrice 703376
Walton 166058
Chauncey 344365
Gavin 943721
Ira 798377
Tyree 665127
Leopoldo 272721
Abraham 659738
September 702625
Tobias 462146
Sherilyn 796810
Francis 453137
Glynis 114310
Lashandra 740330
Johnie 200325
Jon 861734
Herlinda 586654
Cliff 673342
Chris 128935
Jed 337405
Bennett 152914
Korey 216967
Paulita 770846
Lucio 815534
Jeremy 618048
Luz 456328
Dallas 704021
Sung 173346
Launa 850385
Virgilio 619779
Ryan 521177
Elvia 910461
Reed 962174
Nigel 648346
Quyen 454793
Gerardo 385006
Arlette 490144
Andrew 431839
Deon 890988
Wilton 827505
Grayce 353838
Kirby 156077
Rosalyn 438976
Freddy 910320
Breann 591722
Eli 872330
Almeta 444949
Dane 872654
Katelyn 986185
Fairy 844541
Latoya 839298
Tomas 756664
Bridget 132984
Jonathon 118770
Corazon 650507
Daren 643566
Willia 955134
Kiana 870420
Dwight 519038
Lesa 223085
Franklin 439016
Hilario 862565
Lyndon 989000
Kristal 362896
Merri 926049
Sean 459843
Darren 133146
Hugh 455850
Gearldine 293239
Emily 975677
Alesha 288987
Magan 433857
Ara 133740
Marvel 575051
Leopoldo 794901
Kacey 337337
Janell 826295
Julianne 177290
Refugia 726248
Ming 995771
Quintin 382461
Marquis 692171
Dominick 964808
Kendra 486036
Thaddeus 627160
Robbie 478255
Mitchel 268232
Lashell 590738
Asha 268130
Chester 134554
Pasty 450593
Marlyn 145436
Lewis 632032
Lang 403311
Refugio 229609
Ryan 163638
Leota 956114
Saran 294996
Bebe 851647
Alfonso 295139
Noble 124330
Jonah 768865
Mohammad 383382
Palmer 839905
Kraig 403443
Cathryn 635735
Marvin 670140
Joel 539745
Rosalinda 734697
Daryl 682989
Mitsue 294222
Susan 814417
Milton 914370
Jana 910679
Harry 199911
Elisha 442187
Keith 663220
Lakeshia 656534
Charlette 651799
Everette 240385
Jefferson 695928
Tod 720955
Page 193128
Randy 857067
Andre 457208
Al 380906
Gil 159671
Javier 784910
Laquanda 524590
Dexter 848248
Theresa 526962
Tiffiny 819541
Katerine 788970
Lashanda 950290
Ocie 424176
Emory 740094
Emmanuel 635168
Karla 143685
Jesica 648027
Lorretta 656432
Dirk 233593
Eddy 861647
Shonda 176650
Randall 800814
Adelaide 276358
Jack 416730
Randy 905716
Roger 652896
Arturo 157830
Phillip 903606
Muoi 162319
Raleigh 953616
Adalberto 821858
Emanuel 657399
Nu 329977
Lyla 607978
Armand 720102
Craig 156461
Fredric 918076
Janet 921156
Tonette 881478
Andra 147376
Nilsa 631313
Wilber 279056
Albert 426050
Kaila 881064
Daron 550256
Rhona 606646
Rodney 301138
Buck 682234
Aubrey 423006
Stephan 715177
Fabian 128540
Luisa 963266
Deane 512420
Darrell 538297
Andrew 607313
Spring 793658
Gisele 998891
Yong 257050
Art 805435
Romeo 580582
Jerrold 716459
Alida 535988
Amos 118145
Philip 638330
Alvin 555585
Piper 314834
Azalee 448490
Clarence 868865
Elizabeth 865933
Svetlana 155709
Tyree 610111
Jamison 664603
Hollie 859145
Louie 479240
Troy 730014
Bo 811188
Fredda 900511
Isabella 911782
Neida 651352
Johnson 279159
Maud 578410
Russell 743756
Fred 336203
Wayne 348955
Tommy 551531
Russell 499087
Vern 490568
Diego 958129
Marcus 173881
Ilana 171318
Kelley 744924
Chet 826352
Cornelius 675330
Brendan 348612
Janine 723677
Orval 469305
Libby 564396
Luke 894304
Olin 447929
Lakeshia 990341
Melodie 142132
Pat 738569
Royce 960488
Eusebia 427707
Laurence 904903
Etta 558980
Hector 728639
Kyoko 990660
Michel 724942
Brent 349949
Meredith 269145
Rayford 517795
Ray 808683
Novella 769949
Lavonna 773251
Margot 157605
Lucio 432874
Jarod 266517
Loreta 287234
Kristina 715699
Nathaniel 791796
Abby 423476
Reginald 781852
Lashaun 113138
Ollie 177820
Jeanice 863710
Francisco 332897
Vaughn 844768
Noemi 939744
Antony 596386
Manuel 635085
Jae 770887
Jonas 663340
Britt 475292
Lianne 515944
Bret 131132
Alverta 463031
Laurena 546056
Nola 338592
Kermit 780592
Les 162437
Jay 282256
Lennie 404516
Maisie 314807
Coleman 808271
Kristopher 821532
Billy 467460
Veola 639215
Kandi 295336
Augustine 312811
Dino 358423
Dan 760812
Dion 769303
Barrett 152414
Morgan 832886
Brenton 468717
Edmund 251708
Maxwell 775726
Salvatore 195807
Archie 681385
Leif 487183
Sydney 337748
Aleisha 926625
Newton 460504
Herman 790668
Lamar 726990
Bong 526477
Alejandrina 469323
Donetta 116861
Evelyn 468245
Ricardo 365429
Hobert 430984
Quiana 240774
Edythe 292037
Michael 529687
Khadijah 364641
Cody 271618
Mahalia 926284
Jeffrey 224385
Jasper 266007
Chandra 277807
Renata 221301
Will 176357
Maragret 899025
Guillermo 689735
Erminia 274798
Willette 814692
Orpha 365311
Lindsey 146994
Lenard 556883
Fritz 673517
Herbert 673602
Gudrun 678937
Shanika 146167
Duane 350325
Jae 309193
Mignon 663004
Yon 188105
Antony 464311
Greg 358946
Fredric 449728
Aline 353324
Ollie 725816
Ernestina 191837
Margy 209953
Emilio 851514
Ludivina 116881
Frank 472851
Graham 670946
Luther 223092
Leroy 849584
Anika 176870
Georgia 519176
Raymon 464209
Quinn 991036
Jarod 935891
Elijah 247537
Tomi 818406
Dalene 643938
Sung 941810
Shoshana 891455
Darin 679402
Irvin 349361
Eladia 626973
Adriana 320561
Viki 938310
Garret 600632
Sheldon 566953
Domingo 419239
Peggy 219750
Tyler 690557
Antonette 494445
Collette 267187
Reed 229072
Tonya 447531
Guillermo 313149
Wanetta 208863
Katherina 655131
Bulah 416097
Leo 444994
Tamesha 811810
Kathie 517514
Dinorah 481944
Rolland 621804
Shannon 269442
Cheryle 624868
Shizuko 496903
Nakita 676968
Sherell 914931
Tonisha 922127
David 237290
Mark 670436
Juliette 846203
Marlon 726618
Catrina 473339
Karoline 347053
Quentin 884276
Lupe 964177
Roberto 705323
Shawn 594895
Marylou 198259
Armando 405258
Ronna 677436
Mark 681377
Roxie 152572
Jeanne 123266
Hosea 336130
Rene 156033
Elicia 376392
Katerine 175112
Jeffrey 899559
Willis 975513
Royal 388655
Rupert 948438
Miriam 815909
Noelia 961921
Freda 556384
Serita 286613
Leon 832849
Waldo 816700
Edwardo 608583
Salvador 613738
Dan 400303
Patricia 690078
Santiago 150126
Geraldo 281863
Dallas 517673
Sheridan 528289
Sueann 286750
Tenisha 251546
Isaias 581064
Marguerite 643020
Samuel 138955
Antonette 327962
Marita 786060
Stuart 725297
Santos 689215
Gail 952572
Kayce 308279
Kimi 859376
Tommye 851431
Bryant 772566
Dannielle 150598
Shandra 981076
Cole 873703
Kristi 654752
Wilton 879259
Roxann 558331
Alfonso 630001
Alan 810554
Joycelyn 582207
Glady 271753
Trinidad 800717
Alden 809907
Ariel 160755
Loreta 361846
Tom 719891
Azucena 706249
Jona 843473
Jenice 976234
Clarita 889095
Mafalda 605972
Kevin 144522
Al 961327
Anthony 380215
Edmund 460085
Bernice 488651
Jason 431761
Olevia 682672
Michiko 966992
Dusty 280646
Katelyn 895403
Aurelio 883978
Derek 253050
Sheena 308104
Noma 267237
Karrie 183621
Margaret 553123
Ike 588658
Buddy 549924
Rickie 629182
Ira 891136
Garth 994976
Barrett 625460
Arturo 296887
Merle 649522
Ellis 324202
Jeana 824630
Jackeline 916609
Wynell 694220
Luann 922963
Verlie 607557
Jayson 607975
Werner 277455
Young 201252
Johnson 910927
Beulah 172039
Perry 384959
Amada 146320
Israel 495212
Glenn 716277
Drucilla 194302
Raphael 169896
Emanuel 514111
Joseph 612922
Magdalene 866564
Wilma 844300
Granville 417331
Alverta 679519
Silas 671330
Alia 749664
Malik 297809
Melania 692816
Emil 111692
Morton 654489

# **Reshape data into wide or long format**

In [102]:
df4 = pd.melt(df3, id_vars=['Emp_id'],var_name='Column_Name',value_name="Column_value")   
df4.sort_values("Emp_id")

       Emp_id     Column_Name                Column_value
33805  111150       Last Name                     Saddler
8635   111150          E_mail  sanjuana.saddler@gmail.com
28771  111150  Middle Initial                           E
23737  111150      First Name                    Sanjuana
3601   111150          Gender                           F
...       ...             ...                         ...
29943  999800  Middle Initial                           W
34977  999800       Last Name                   Stillwell
4773   999800          Gender                           F
19875  999800         Country                      Mercer
14841  999800          Salary                       62021

[35238 rows x 3 columns]